platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Swifjection_Tests' do
  pod 'Swifjection', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end

target 'Example' do
  pod 'Swifjection', :path => '../'
end
